### ISSUE TITLE
Final API review by Betsol

### ISSUE THREAD

**Issue by nckhell** [awell-health/sol-scheduling#57]
We want the Betsol team to do a final review of the [API spec](https://github.com/awell-health/sol-scheduling/blob/main/docs/api.spec.yaml) ([view it on the web](https://awell-health.github.io/sol-scheduling/)).

If any issues are found, the Betsol team can edit the API spec directly in the code and submit a PR (please refer to this issue). Alternatively, add comments to this GitHub issue, and we’ll happily address the changes from there.

**Comment by nckhell** [comment]
## Age validation

Updated the AgePreference schema in the API documentation to reflect a new minimum age value of 5.

https://github.com/awell-health/sol-scheduling/pull/58

**Comment by RohanSanjaySavalgi** [comment]
I have reviewed the complete API documentation using the Swagger Web UI.
