### ISSUE TITLE
Changes to first and last name in API response

### ISSUE THREAD

**Issue by RohanSanjaySavalgi** [awell-health/sol-scheduling#60]
Inside two APIs the first name and last name would be changed. Currently we are sending a string named as "name" with "<**firstname**> <**lastname**>" as the value.

Now we want to send two fields called as "**firstname**" and "**lastname**" with the respective values. This change is being made so that the front end can be responsible on how the name of each provider can be show inside the UI.

_This is still not implemented inside the APIs. This change can be expected after SOL gives us a green signal to push_ #

**Comment by nckhell** [comment]
This change has been made in the API.
