### ISSUE TITLE
Production ready APIs

### ISSUE THREAD

**Issue by RohanSanjaySavalgi** [awell-health/sol-scheduling#61]
We have a new set of API where in the base path of these APIs have changed. This change is coming along due to the fact that we wanted to have rate-limiting on our APIs for obvious security purposes. The new set of APIs are attached below:

Base API path: **https://func-smh-ss-webapi-prod-001.solmentalhealth.com/api**

Example paths:

1. https://func-smh-ss-webapi-prod-001.solmentalhealth.com/api/v2/provider
2. https://func-smh-ss-webapi-prod-001.solmentalhealth.com/api/event/list
3. https://func-smh-ss-webapi-prod-001.solmentalhealth.com/api/event?providerId=<provider_id>&eventId=<event_id>
4. https://func-smh-ss-webapi-prod-001.solmentalhealth.com/api/provider/info?providerId=<provider_id>
5. https://func-smh-ss-webapi-prod-001.solmentalhealth.com/api/event/book
_* any missed APIs will have the updated base path and route similar to these_

The APIs which are currently being used are also serving traffic, but after hearing from your end, Betsol will go ahead and stop receiving traffic on these older APIs.

_Still the stagging APIs will remain the same and **DO NOT** have rate-limiting applied to them._

**Comment by nckhell** [comment]
@RohanSanjaySavalgi @Ukulsum16 Can you confirm this new API endpoint is up and running in production? Additionally, can you also review and approve the linked PR?

**Comment by RohanSanjaySavalgi** [comment]
Hey @nckhell, all the APIs which are provided by us are already up and running. We can switch to these rate limited APIs.

FYI @Ukulsum16
